server.host: "0.0.0.0"
server.ssl.enabled: true
server.ssl.key: /usr/share/kibana/config/certs/kibana/kibana.key
server.ssl.certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
elasticsearch.hosts: ["https://es01:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_PASSWORD}"
elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certs/ca/ca.crt
elasticsearch.ssl.verificationMode: certificate

#server:
#  publicBaseUrl:
