image_adapter:
    resource: ../src/Image/Infrastructure/Web
    type: attribute

user_adapter:
    resource: ../src/User/Infrastructure/Web
    type: attribute

api_login:
    path: /api/login
    methods: [POST]
