# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default:
            url: '%env(ELASTIC_URL)%'
            username: '%env(ELASTIC_USERNAME)%'
            password: '%env(ELASTIC_PASSWORD)%'
            ssl: true
            transport: 'Https'
            curl:
                !php/const:CURLOPT_SSL_VERIFYHOST: 2
                !php/const:CURLOPT_SSL_VERIFYPEER: 1
                !php/const:CURLOPT_CAINFO: '%elastic_ca_cert_path%'

    indexes:
        images:
            properties:
                id:
                    type: integer
                filename:
                    type: text
                description:
                    type: text
                createdAt:
                    type: date
                showOnHomepage:
                    type: boolean
                objectKey:
                    type: keyword
            persistence:
                driver: orm
                model: App\Image\Domain\Entity\Image
                provider: ~
                finder: ~
                listener:
                    insert: false
                    update: false
                    delete: false
            settings:
                index:
                    number_of_shards: 1
                    number_of_replicas: 0
