framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
#            async:
#                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                options:
#                    auto_setup: true
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # failed: 'doctrine://default?queue_name=failed'
             sync: 'sync://'

        routing:
            'App\Image\Application\UploadImage\ElasticsearchIndexImageMessage': sync
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'